### ISSUE TITLE
Monitoring avec Grafana

### ISSUE THREAD

**Issue by JPLavigne** [JPLavigne/LOG680-tp1-gr01-eq11#41]
Ce sous-requis nécessite d’établir la connexion entre l’instance Grafana et votre base de données.
Pour ce sous-requis, vous devrez créer un dashboard sur Grafana. Les plugins nécessaires sont présents sur l’instance Grafana.

**Comment by TheFinalDay** [comment]
Le Dashboard Grafana est bel et bien connecté à la base de données et accessible à l'adresse suivante:
https://log680.grafana.vincentboivin.ca/?orgId=12
(avec les coordonées données par le chargé de lab dans discord)

![image](https://user-images.githubusercontent.com/19574522/143662172-7da5d48f-5a76-46d8-bf32-18d8a09455ba.png)
